/**
 * Image URL helpers for generating responsive srcset with pre-generated variants.
 *
 * Variants are generated by scripts/sync-photos.py:
 * - Original: /media/portfolio/portraits/2026-portrait-001.jpg
 * - 400w WebP: /media/portfolio/portraits/2026-portrait-001-400w.webp
 * - 800w WebP: /media/portfolio/portraits/2026-portrait-001-800w.webp
 * - etc.
 */

// Available width breakpoints (generated by sync script)
export const IMAGE_WIDTHS = [400, 800, 1200, 1920] as const
export type ImageWidth = (typeof IMAGE_WIDTHS)[number]

/**
 * Get the variant URL for a given image at a specific width.
 * Falls back to original if variant doesn't exist.
 */
export function getVariantUrl(
  src: string,
  width: ImageWidth,
  format: 'webp' | 'jpg' = 'webp'
): string {
  // Extract path without extension
  const lastDot = src.lastIndexOf('.')
  if (lastDot === -1) return src

  const basePath = src.slice(0, lastDot)
  const ext = format === 'webp' ? '.webp' : '.jpg'

  return `${basePath}-${width}w${ext}`
}

/**
 * Generate srcset string for responsive images.
 * Uses WebP variants generated by the sync script.
 */
export function getSrcSet(src: string, widths: readonly ImageWidth[] = IMAGE_WIDTHS): string {
  return widths
    .map((w) => `${getVariantUrl(src, w)} ${w}w`)
    .join(', ')
}

/**
 * Generate sizes attribute based on common layout patterns.
 *
 * These values tell the browser how large the image will display,
 * so it can pick the appropriate variant from srcset.
 */
export function getSizes(pattern: 'gallery' | 'hero' | 'thumbnail' = 'gallery'): string {
  switch (pattern) {
    case 'hero':
      return '100vw'
    case 'thumbnail':
      return '(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 200px'
    case 'gallery':
    default:
      // Justified layout: images scale with row height
      // Mobile (< 768px): 320px row height → landscape ~480px wide, portrait ~215px
      // Desktop (≥ 768px): 600px row height → landscape ~900px wide, portrait ~400px
      // Use generous estimates so browser picks sharp variants
      return '(max-width: 767px) 480px, 900px'
  }
}

/**
 * Get the appropriate default src based on context.
 * - gallery: 800w for grid thumbnails
 * - hero: 1200w for hero images
 * - lightbox: 1920w WebP for optimized full-screen viewing (90%+ size reduction vs original)
 */
export function getDefaultSrc(src: string, context: 'gallery' | 'hero' | 'lightbox' = 'gallery'): string {
  if (context === 'lightbox') {
    // 1920w WebP is visually identical on most displays, saves 4-18MB per image
    return getVariantUrl(src, 1920)
  }
  const width = context === 'hero' ? 1200 : 800
  return getVariantUrl(src, width)
}

/**
 * Check if an image path is a portfolio image that has variants.
 * Only portfolio images have variants generated.
 */
export function hasVariants(src: string): boolean {
  return src.startsWith('/media/portfolio/')
}
