_page: site
nav_logo: /media/site/logos/black-transparent-bg-logo.png
nav_logo_white: /media/site/logos/white-transparent-bg-logo.png.png
footer_logo: /media/site/logos/1 white transparent.png
logo_alt: Sol Photography
