_page: site
nav_logo: /media/site/logos/2026/Sol_Photo_Lockup_Primary_Black.svg
nav_logo_white: /media/site/logos/2026/Sol_Photo_Lockup_Primary_White.svg
footer_logo: /media/site/logos/2026/Sol_Photo_Stamp_White.svg
logo_alt: Sol Photography
